### ISSUE TITLE
Bug: hamburger menu button seems broken

### ISSUE THREAD

**Issue by zdylag** [Vgr255/TwitchCordBot#19]
The hamburger menu does not cause anything to happen for me, should it? Or should it be removed?

**Comment by thiderman** [comment]
Small oversight on my part. The hamburger is not the same as the un..hamburgered menu, and I missed that and thus it doesn't have any content right now. Should be very fixable!

**Comment by thiderman** [comment]
This was fixed in the finalization of the design! :eyes:
