### ISSUE TITLE
GitHub issue templates

### ISSUE THREAD

**Issue by zdylag** [Vgr255/TwitchCordBot#20]
It might be nice to make the process of opening tickets easier, and make it quicker to know what is a bug vs feature request vs whatever.

**Comment by thiderman** [comment]
Do you know of a project that has some good ones we can borrow from?

**Comment by zdylag** [comment]
I don't know about good, but I made a repo a while back to play with this sort of thing:

https://github.com/zdylag/GoSeed/tree/main/.github/ISSUE_TEMPLATE

**Comment by Vgr255** [comment]
Fixed in #23
