### ISSUE TITLE
Task: replace the default branch of the repository

### ISSUE THREAD

**Issue by zdylag** [Vgr255/TwitchCordBot#26]
This is something many organizations (including GitHub) have been making over the last year or so in order to be a more inclusive place.

Specifically moving away from `master` which has many harmful associations, and to `main` which is much more neutral.

For GitHub specifics: https://github.com/github/renaming

For some other industry examples: https://www.zdnet.com/article/ibm-microsoft-staff-rally-to-remove-racially-insensitive-language-from-products/

### Affected Functionality
This should not impact any actual code behavior.

**Comment by Vgr255** [comment]
Done! Thanks for bringing attention to this :)
