### ISSUE TITLE
Bug: Keys Incorrectly Reported as Not Obtained During Current Run

### ISSUE THREAD

**Issue by dzadok** [Vgr255/TwitchCordBot#32]
Keys show as not obtained during the current run, even when they are.

### Step(s) to Reproduce
(Not Sure if this always happens, but the current run as of 9/14/22 1:07pm EDT shows the issue under /current)

### Expected Result
Keys should show what floor it was obtained on, and ideally what relic was skipped for the Sapphire Key.

### Actual Outcome
The text "This key hasn't been obtained yet." is displayed.

**Comment by dzadok** [comment]
I think this always happens in the current run, and always works correctly in historical runs. But my sample size for current runs is only two.

**Comment by dzadok** [comment]
I edited the issue as I observed the same thing happening with the Emerald Key.

**Comment by thiderman** [comment]
Fixed it! Small error for the `/current` page that now has the same logic as the history pages.

Thanks for the report and the continued updates! :purple_heart:
